In [2]:
import pandas as pd

In [42]:
# Define the path to the CSV file
file_path = "Freedom Indices.xlsx"

# Read the excel file into a pandas DataFrame
freedom_indices = pd.read_excel(file_path, sheet_name='FIW06-24')
freedom_total=pd.read_excel(file_path, sheet_name='FIW03-05')

# Display the first few rows of the DataFrame
print(freedom_indices.head(5))

  Country/Territory   Region C/T?  Edition Status  PR Rating  CL Rating   A  \
0          Abkhazia  Eurasia    t     2024     PF          5          5   5
1       Afghanistan     Asia    c     2024     NF          7          7   0
2           Albania   Europe    c     2024     PF          3          3   9
3           Algeria   Africa    c     2024     NF          6          5   3
4           Andorra   Europe    c     2024      F          1          1  12

    B   C  ...  Unnamed: 25  Unnamed: 26  Unnamed: 27  Unnamed: 28  \
0   8   4  ...          NaN          NaN          NaN          NaN
1   0   1  ...          NaN          NaN          NaN          NaN
2  12   7  ...          NaN          NaN          NaN          NaN
3   4   3  ...          NaN          NaN          NaN          NaN
4  15  11  ...          NaN          NaN          NaN          NaN

   Unnamed: 29  Unnamed: 30  Unnamed: 31  Unnamed: 32  Unnamed: 33   x
0          NaN          NaN          NaN          NaN          NaN NaN
1          NaN          NaN          NaN          NaN          NaN NaN
2          NaN          NaN          NaN          NaN          NaN NaN
3          NaN          NaN          NaN          NaN          NaN NaN
4          NaN          NaN          NaN          NaN          NaN NaN

[5 rows x 35 columns]

In [43]:
# Removing columns that contain 'Unnamed' in their names
freedom_indices = freedom_indices.loc[:, ~freedom_indices.columns.str.contains('^Unnamed')]
freedom_indices = freedom_indices.iloc[:, :-1]
# Display the remaining columns
remaining_columns = freedom_indices.columns.tolist()
remaining_columns

['Country/Territory',
 'Region',
 'C/T?',
 'Edition',
 'Status',
 'PR Rating',
 'CL Rating',
 'A',
 'B',
 'C',
 'Add Q',
 'Add A',
 'PR',
 'D',
 'E',
 'F',
 'G',
 'CL',
 'Total']

In [44]:
freedom_indices = freedom_indices.drop(columns=["Add A", "Add Q"])

In [45]:
# Dictionary to map current column names to their definitions
column_mapping = {
    "Country/Territory": "Location Name",
    "Region": "Region",
    "C/T?": "Country or Territory?",
    "Edition": "Edition",
    "Status": "Freedom Status",
    "PR Rating": "Political Rights Rating",
    "CL Rating": "Civil Liberties Rating",
    "A": "Electoral Process",
    "B": "Political Pluralism and Participation",
    "C": "Functioning of Government",
    "Add Q": "Additional Discretionary Question (B)",
    "Add A": "Additional Discretionary Question A",
    "PR": "Political Rights category",
    "D": "Freedom of Expression and Belief",
    "E": "Associational and Organizational Rights",
    "F": "Rule of Law",
    "G": "Personal Autonomy and Individual Rights",
    "CL": "Civil Liberties category",
    "Total": "Total"
}

# Rename the columns
freedom_indices.rename(columns=column_mapping, inplace=True)

In [46]:
#add percentage column for total out of actual summed total
total_sum = freedom_indices["Total"].sum()
freedom_indices["Total Freedom Ratio"] = freedom_indices["Total"] / total_sum
freedom_indices.head(5)

,Location Name,Region,Country or Territory?,Edition,Freedom Status,Political Rights Rating,Civil Liberties Rating,Electoral Process,Political Pluralism and Participation,Functioning of Government,Political Rights category,Freedom of Expression and Belief,Associational and Organizational Rights,Rule of Law,Personal Autonomy and Individual Rights,Civil Liberties category,Total,Total Freedom Ratio
0,Abkhazia,Eurasia,t,2024,PF,5,5,5,8,4,17,8,5,4,5,22,39,0.000168
1,Afghanistan,Asia,c,2024,NF,7,7,0,0,1,1,0,3,0,2,5,6,0.000026
2,Albania,Europe,c,2024,PF,3,3,9,12,7,28,13,8,10,9,40,68,0.000294
3,Algeria,Africa,c,2024,NF,6,5,3,4,3,10,6,3,6,7,22,32,0.000138
4,Andorra,Europe,c,2024,F,1,1,12,15,11,38,14,11,15,15,55,93,0.000402

In [47]:
# Mapping for the conversion
freedom_status_map = {
    "PF": "Partly Free",
    "F": "Free",
    "NF": "Not Free"
}

# Applying the conversion
freedom_indices["Freedom Status"] = freedom_indices["Freedom Status"].map(freedom_status_map)
freedom_indices

,Location Name,Region,Country or Territory?,Edition,Freedom Status,Political Rights Rating,Civil Liberties Rating,Electoral Process,Political Pluralism and Participation,Functioning of Government,Political Rights category,Freedom of Expression and Belief,Associational and Organizational Rights,Rule of Law,Personal Autonomy and Individual Rights,Civil Liberties category,Total,Total Freedom Ratio
0,Abkhazia,Eurasia,t,2024,Partly Free,5,5,5,8,4,17,8,5,4,5,22,39,0.000168
1,Afghanistan,Asia,c,2024,Not Free,7,7,0,0,1,1,0,3,0,2,5,6,0.000026
2,Albania,Europe,c,2024,Partly Free,3,3,9,12,7,28,13,8,10,9,40,68,0.000294
3,Algeria,Africa,c,2024,Not Free,6,5,3,4,3,10,6,3,6,7,22,32,0.000138
4,Andorra,Europe,c,2024,Free,1,1,12,15,11,38,14,11,15,15,55,93,0.000402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3964,Vietnam,Asia,c,2006,Not Free,7,5,0,1,1,2,3,2,4,8,17,19,0.000082
3965,Western Sahara,Africa,t,2006,Not Free,7,6,0,0,0,-2,3,2,0,5,10,8,0.000035
3966,Yemen,Middle East,c,2006,Partly Free,5,5,4,6,3,13,7,3,3,5,18,31,0.000134
3967,Zambia,Africa,c,2006,Partly Free,4,4,5,11,6,22,11,8,8,7,34,56,0.000242
3968,Zimbabwe,Africa,c,2006,Not Free,7,6,1,4,0,5,5,3,1,1,10,15,0.000065

In [48]:
import csv
from datetime import datetime
from pprint import pprint
import pandas as pd
import numpy as np

In [51]:
with open("Financial-Inclusion.csv",'r') as infile:
    text = list(csv.reader(infile))
    header = text[0]
    data = text[1:]

states = data[0:572]
states_df = pd.DataFrame(states, columns=header)
states_df = states_df[states_df["Country name"] != "Iceland"]
states_df.replace("", np.nan, inplace=True)
df_cleaned = states_df.dropna(axis=1, how='any')
regions = data[573:595]
region_df = pd.DataFrame(regions, columns=header)
region_df.replace("", np.nan, inplace=True)
df_cleaned1 = region_df.dropna(axis=1, how='any')

# 44 columns
# We liked the first 12, but I agree that we should run regression and let it decide for us!

df_cleaned

,Country name,Country code,Year,Adult populaiton,Region,Account (% age 15+),Financial institution account (% age 15+),Owns a credit card (% age 15+),Owns a debit card (% age 15+),Owns a debit or credit card (% age 15+),...,"Saved at a financial institution, young (% ages 15-24)","Saved at a financial institution, older (% age 25+)","Borrowed from a formal financial institution, female (% age 15+)","Borrowed from a formal financial institution, male (% age 15+)","Borrowed from a formal financial institution, young (% ages 15-24)","Borrowed from a formal financial institution, older (% age 25+)","Borrowed from family or friends, female (% age 15+)","Borrowed from family or friends, male (% age 15+)","Borrowed from family or friends, young (% ages 15-24)","Borrowed from family or friends, older (% age 25+)"
0,Afghanistan,AFG,2011,15124473,South Asia,9%,9%,1%,5%,5%,...,2%,3%,5%,10%,5%,9%,21%,39%,27%,32%
1,Afghanistan,AFG,2014,17300802,South Asia,10%,10%,1%,2%,2%,...,4%,3%,1%,8%,4%,5%,19%,26%,20%,24%
2,Afghanistan,AFG,2017,19718214,South Asia,15%,15%,1%,3%,3%,...,4%,4%,3%,4%,1%,5%,24%,28%,25%,27%
3,Afghanistan,AFG,2021,22647496,South Asia,10%,10%,0%,3%,3%,...,0%,2%,1%,3%,2%,2%,64%,57%,59%,61%
4,Albania,ALB,2011,2258900,Europe & Central Asia (excluding high income),28%,28%,11%,21%,24%,...,7%,9%,6%,9%,5%,8%,13%,8%,8%,12%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,Zambia,ZMB,2021,10291819,Sub-Saharan Africa (excluding high income),49%,24%,2%,10%,11%,...,5%,10%,6%,8%,4%,8%,38%,49%,41%,44%
568,Zimbabwe,ZWE,2011,7414228,Sub-Saharan Africa (excluding high income),40%,40%,6%,28%,29%,...,8%,23%,4%,6%,1%,7%,56%,59%,55%,59%
569,Zimbabwe,ZWE,2014,7712326,Sub-Saharan Africa (excluding high income),32%,17%,2%,14%,14%,...,3%,6%,4%,4%,2%,6%,55%,56%,52%,57%
570,Zimbabwe,ZWE,2017,8044282,Sub-Saharan Africa (excluding high income),55%,28%,1%,22%,22%,...,4%,6%,4%,6%,3%,5%,37%,38%,36%,39%
571,Zimbabwe,ZWE,2021,8633711,Sub-Saharan Africa (excluding high income),60%,29%,0%,18%,18%,...,4%,4%,2%,4%,2%,3%,37%,47%,43%,42%

In [54]:
freedom_indices.loc[:, 'Edition'] = freedom_indices['Edition'].astype(int)
df_cleaned.loc[:, 'Year'] = df_cleaned['Year'].astype(int)
merged_df = pd.merge(freedom_indices, df_cleaned, left_on=['Location Name', 'Edition'], right_on=['Country name', 'Year'])
merged_df
#merged_df.columns

,Location Name,Region_x,Country or Territory?,Edition,Freedom Status,Political Rights Rating,Civil Liberties Rating,Electoral Process,Political Pluralism and Participation,Functioning of Government,...,"Saved at a financial institution, young (% ages 15-24)","Saved at a financial institution, older (% age 25+)","Borrowed from a formal financial institution, female (% age 15+)","Borrowed from a formal financial institution, male (% age 15+)","Borrowed from a formal financial institution, young (% ages 15-24)","Borrowed from a formal financial institution, older (% age 25+)","Borrowed from family or friends, female (% age 15+)","Borrowed from family or friends, male (% age 15+)","Borrowed from family or friends, young (% ages 15-24)","Borrowed from family or friends, older (% age 25+)"
0,Azerbaijan,Eurasia,c,2022,Not Free,7,7,0,2,0,...,5%,4%,17%,22%,15%,20%,38%,45%,32%,44%
1,Botswana,Africa,c,2022,Free,3,2,10,10,8,...,18%,17%,8%,12%,6%,11%,27%,35%,41%,28%
2,Chad,Africa,c,2022,Not Free,7,6,0,1,0,...,6%,9%,8%,9%,7%,9%,41%,46%,42%,44%
3,Comoros,Africa,c,2022,Partly Free,5,4,5,7,4,...,6%,14%,7%,10%,5%,10%,25%,33%,28%,29%
4,Eswatini,Africa,c,2022,Not Free,7,6,0,1,0,...,8%,16%,9%,10%,8%,10%,55%,55%,52%,56%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,Uruguay,Americas,c,2011,Free,1,1,12,16,11,...,3%,6%,14%,16%,4%,17%,6%,7%,6%,7%
509,Uzbekistan,Eurasia,c,2011,Not Free,7,7,0,0,0,...,0%,1%,1%,2%,1%,2%,10%,13%,8%,13%
510,Vietnam,Asia,c,2011,Not Free,7,5,0,1,1,...,3%,10%,15%,17%,10%,18%,27%,35%,36%,30%
511,Zambia,Africa,c,2011,Partly Free,3,4,8,11,6,...,6%,15%,8%,4%,2%,9%,41%,42%,37%,44%
512,Zimbabwe,Africa,c,2011,Not Free,6,6,2,4,2,...,8%,23%,4%,6%,1%,7%,56%,59%,55%,59%